<?php
defined('BASEPATH') OR exit('No direct script access allowed');

$config['admin_form_config_loaded'] = true;

$config['form_login_config'] = [
	[
		'field' => 'id',
		'label' => 'lang:user.id',
		'rules' => 'trim|required',
		'errors' => [],
		'category' => 'basic',
		'type' => 'text',
		'icon' => 'ri-user-line',
		'attributes' => [
			'autocapitalize' => 'none',
			'autocomplete' => 'off',
			'placeholder' => 'Enter The User ID',
		],
	],
	[
		'field' => 'password',
		'label' => 'lang:user.password',
		'rules' => 'trim|required',
		'errors' => [],
		'category' => 'basic',
		'type' => 'password',
		'attributes' => [
			'autocomplete' => 'new-password',
			'placeholder' => 'Password Dots',
		],
	],
	[
		'field' => 'autologin',
		'label' => 'lang:auth.autologin',
		'rules' => '',
		'errors' => [],
		'category' => 'basic',
		'type' => 'checkbox',
		'subtype' => 'single',
		'attributes' => [],
		'form_attributes' => [],
	],
];

$config['form_find_id_config'] = [
	[
		'field' => 'email',
		'label' => 'lang:user.email',
		'rules' => 'trim|required|is_unique[user.email.user_id]',
		'category' => 'basic',
		'type' => 'email',
		'icon' => 'ri-font-family',
		'attributes' => [
			'autocapitalize' => 'none',
			'autocomplete' => 'off',
			'placeholder' => 'Enter The User Email',
		],
	],
	[
		'field' => 'tel',
		'label' => 'lang:user.tel',
		'form' => true,
		'rules' => 'trim|required',
		'errors' => [],
		'category' => 'basic',
		'type' => 'tel',
		'subtype' => 'cleave-hp',
		'icon' => null,
		'form_text' => '',
		'attributes' => [],
		'default' => '',
		'list' => true,
		'list_attributes' => [],
	],
];

$config['form_find_password_config'] = [
	[
		'field' => 'id',
		'label' => 'lang:user.id',
		'rules' => 'trim|required',
		'category' => 'basic',
		'icon' => 'ri-font-family',
		'attributes' => [
			'autocapitalize' => 'none',
			'autocomplete' => 'off',
			'placeholder' => 'Enter The User ID',
		],
	],
	[
		'field' => 'email',
		'label' => 'lang:user.email',
		'rules' => 'trim|required',
		'category' => 'basic',
		'type' => 'email',
		'icon' => 'ri-font-family',
		'attributes' => [
			'autocapitalize' => 'none',
			'autocomplete' => 'off',
			'placeholder' => 'Enter The User Email',
		],
	],
	[
		'field' => 'tel',
		'label' => 'lang:user.tel',
		'form' => true,
		'rules' => 'trim|required',
		'errors' => [],
		'category' => 'basic',
		'type' => 'tel',
		'subtype' => 'cleave-hp',
		'icon' => null,
		'form_text' => '',
		'attributes' => [],
		'default' => '',
		'list' => true,
		'list_attributes' => [],
	],
];

$config['form_administrators_config'] = [
	[
		'field' => 'user_id',
		'label' => 'lang:user.user_id',
		'form' => true,
		'rules' => 'trim|required_mod[edit]',
		'errors' => [],
		'category' => 'basic',
		'type' => 'hidden',
		'subtype' => 'identifier',
		'list' => false,
	],
	[
		'field' => 'id',
		'label' => 'lang:user.id',
		'rules' => 'trim|required|min_length[4]|is_unique[user.id.user_id]',
		'form' => true,
		'errors' => [],
		'category' => 'custom',
		'type' => 'text',
		'subtype' => 'unique',
		'icon' => 'ri-user-line',
		'form_text' => 'Please enter at least 4 characters',
		'attributes' => [
			'autocapitalize' => 'none',
			'autocomplete' => 'off',
			'placeholder' => 'Enter The User ID',
		],
		'form_attributes' => [
			'detect_changed' => true,
			'editable' => false,
			'with_btn' => true,
			'btn_type' => 'dup_check',
			'btn_params' => '{"key":"id", "title":"아이디"}',
			'text_type' => 'eng|num',
		],
		'list' => true,
	],
	[
		'field' => 'password',
		'label' => 'lang:user.password',
		'rules' => 'trim|required_mod[add]|min_length[4]|max_length[15]',
		'form' => true,
		'errors' => [],
		'category' => 'group',
		'type' => 'password',
		'icon' => 'svg:ri-lock-password-line',
		'form_text' => 'Please enter 4 to 15 characters, including letters and numbers',
		'attributes' => [
			'autocomplete' => 'new-password',
			'placeholder' => 'Password Dots',
		],
		'form_attributes' => [
			'detect_changed' => true,
		],
		'group' => 'user_password',
		'group_attributes' => [
			'envelope_name' => false,
			'label' => 'lang:user.password',
			'form_text' => '',
			'type' => 'new_password',
			'key' => 'password',
		],
		'list' => false,
	],
	[
		'field' => 'password_confirm',
		'label' => 'lang:user.password_confirm',
		'rules' => 'trim|required_mod[add]|matches[password]',
		'form' => true,
		'errors' => [],
		'category' => 'group',
		'type' => 'password',
		'subtype' => 'password_confirm',
		'icon' => 'svg:ri-lock-password-fill',
		'form_text' => 'Please Repeat The Password',
		'attributes' => [
			'autocomplete' => 'new-password',
			'placeholder' => 'Password Dots',
		],
		'form_attributes' => [
			'detect_changed' => true,
		],
		'group' => 'user_password',
		'group_attributes' => [
			'key' => 'password_confirm',
		],
		'list' => false,
	],
	[
		'field' => 'name',
		'label' => 'lang:user.name',
		'rules' => 'trim|required',
		'form' => true,
		'list' => true,
	],
	[
		'field' => 'email',
		'label' => 'lang:user.email',
		'rules' => 'trim|required|is_unique[user.email.user_id]',
		'form' => true,
		'category' => 'custom',
		'type' => 'text',
		'subtype' => 'unique',
		'icon' => 'ri-font-family',
		'attributes' => [
			'placeholder' => '이메일을 입력하세요',
		],
		'form_attributes' => [
			'editable' => false,
			'with_btn' => true,
			'btn_type' => 'dup_check',
			'btn_params' => '{"key":"email", "title":"이메일"}',
			'text_type' => 'email',
		],
		'list' => true,
	],
	[
		'field' => 'tel',
		'label' => 'lang:user.tel',
		'form' => true,
		'rules' => 'trim|required',
		'errors' => [],
		'category' => 'basic',
		'type' => 'tel',
		'subtype' => 'cleave-hp',
		'icon' => null,
		'form_text' => '',
		'attributes' => [],
		'default' => '',
		'list' => true,
		'list_attributes' => [],
	],
	[
		'field' => 'recent_dt',
		'label' => 'lang:common.recent_dt',
		'form' => true,
		'rules' => 'trim',
		'errors' => [],
		'category' => 'basic',
		'type' => 'text',
		'subtype' => 'readonly',
		'icon' => 'ri-calendar-line',
		'form_text' => '',
		'attributes' => [
			'placeholder' => 'YYYY-MM-DD',
		],
		'form_attributes' => [
			'view_mod' => 'edit',
		],
		'list' => true,
	],
];

$config['form_students_config'] = [
	[
		'field' => 'student_id',
		'label' => 'lang:student.student_id',
		'form' => true,
		'rules' => 'trim|required_mod[edit]',
		'errors' => [],
		'category' => 'basic',
		'type' => 'hidden',
		'subtype' => 'identifier',
		'list' => false,
	],
	[
		'field' => 'user_id',
		'label' => 'lang:user.user_id',
		'form' => true,
		'rules' => 'trim|required_mod[edit]',
		'errors' => [],
		'category' => 'basic',
		'type' => 'hidden',
		'list' => false,
	],
	[
		'field' => 'user_cd',
		'label' => 'lang:user.user_cd',
		'form' => true,
		'rules' => 'trim',
		'category' => 'basic',
		'type' => 'hidden',
		'default' => 'USR002',
		'list' => false,
	],
	[
		'field' => 'id',
		'label' => 'lang:user.id',
		'rules' => 'trim|required|min_length[4]|is_unique[user.id.user_id]',
		'form' => true,
		'errors' => [],
		'category' => 'custom',
		'type' => 'text',
		'subtype' => 'unique',
		'icon' => 'ri-user-line',
		'form_text' => 'Please enter at least 4 characters',
		'attributes' => [
			'autocapitalize' => 'none',
			'autocomplete' => 'off',
			'placeholder' => '아이디를 입력하세요',
		],
		'form_attributes' => [
			'editable' => false,
			'with_btn' => true,
			'btn_type' => 'dup_check',
			'btn_params' => '{"key":"id", "title":"아이디"}',
			'text_type' => 'eng|num',
		],
		'list' => true,
	],
	[
		'field' => 'password',
		'label' => 'lang:user.password',
		'rules' => 'trim|required_mod[add]|min_length[4]|max_length[15]',
		'form' => true,
		'errors' => [],
		'category' => 'group',
		'type' => 'password',
		'icon' => 'svg:ri-lock-password-line',
		'form_text' => 'Please enter 4 to 15 characters, including letters and numbers',
		'attributes' => [
			'autocomplete' => 'new-password',
			'placeholder' => 'Password Dots',
		],
		'form_attributes' => [
			'detect_changed' => true,
		],
		'group' => 'user_password',
		'group_attributes' => [
			'envelope_name' => false,
			'label' => 'lang:user.password',
			'form_text' => '',
			'type' => 'new_password',
			'key' => 'password',
		],
		'list' => false,
	],
	[
		'field' => 'password_confirm',
		'label' => 'lang:user.password_confirm',
		'rules' => 'trim|required_mod[add]|matches[password]',
		'form' => true,
		'errors' => [],
		'category' => 'group',
		'type' => 'password',
		'subtype' => 'password_confirm',
		'icon' => 'svg:ri-lock-password-fill',
		'form_text' => 'Please Repeat The Password',
		'attributes' => [
			'autocomplete' => 'new-password',
			'placeholder' => 'Password Dots',
		],
		'form_attributes' => [
			'detect_changed' => true,
		],
		'group' => 'user_password',
		'group_attributes' => [
			'key' => 'password_confirm',
		],
		'list' => false,
	],
	[
		'field' => 'name',
		'label' => 'lang:user.name',
		'rules' => 'trim|required',
		'form' => true,
		'list' => true,
	],
	[
		'field' => 'email',
		'label' => 'lang:user.email',
		'rules' => 'trim|required|is_unique[user.email.user_id]',
		'form' => true,
		'category' => 'custom',
		'type' => 'text',
		'subtype' => 'unique',
		'icon' => 'ri-font-family',
		'attributes' => [
			'placeholder' => 'Enter The User Email',
		],
		'form_attributes' => [
			'editable' => false,
			'with_btn' => true,
			'btn_type' => 'dup_check',
			'btn_params' => '{"key":"email", "title":"이메일"}',
			'text_type' => 'email',
		],
		'list' => true,
	],
	[
		'field' => 'tel',
		'label' => 'lang:user.tel',
		'form' => true,
		'rules' => 'trim|required',
		'errors' => [],
		'category' => 'basic',
		'type' => 'tel',
		'subtype' => 'cleave-hp',
		'icon' => null,
		'form_text' => '',
		'attributes' => [],
		'default' => '',
		'list' => true,
		'list_attributes' => [],
	],
	[
		'field' => 'code',
		'label' => 'lang:student.code',
		'form' => true,
		'rules' => 'trim|required',
		'errors' => [],
		'category' => 'basic',
		'icon' => null,
		'form_text' => '',
		'attributes' => [],
		'default' => '',
		'list' => true,
		'list_attributes' => [],
	],
	[
		'field' => 'grade',
		'label' => 'lang:student.grade',
		'form' => true,
		'rules' => 'trim|required',
		'errors' => [],
		'category' => 'basic',
		'type' => 'select',
		'subtype' => 'selectpicker',
		'attributes' => [
			'placeholder' => 'Select The Grade',
		],
		'option_attributes' => [
			'option_type' => 'field',
		],
		'default' => '',
		'list' => true,
		'list_attributes' => [],
	],
	[
		'field' => 'disabilities_yn',
		'label' => 'lang:student.disabilities_yn',
		'form' => true,
		'rules' => 'trim',
		'errors' => [],
		'category' => 'basic',
		'type' => 'checkbox',
		'subtype' => 'single',
		'option_attributes' => [
			'option_type' => 'static',
			'option_data' => [
				'Y' => 'lang:student.disabilities_yn',
			],
		],
		'form_attributes' => [
			'detect_changed' => true,
		],
		'default' => '',
		'list' => true,
		'list_attributes' => [],
	],
	[
		'field' => 'aac_yn',
		'label' => 'lang:student.aac_yn',
		'form' => true,
		'rules' => 'trim',
		'errors' => [],
		'category' => 'basic',
		'type' => 'checkbox',
		'subtype' => 'single',
		'option_attributes' => [
			'option_type' => 'static',
			'option_data' => [
				'Y' => 'lang:student.aac_yn',
			],
		],
		'form_attributes' => [
			'detect_changed' => true,
		],
		'default' => '',
		'list' => true,
		'list_attributes' => [],
	],
    [
        'field' => 'approve_yn',
        'label' => 'lang:version.approve_yn',
        'form' => true,
        'category' => 'basic',
        'type' => 'checkbox',
        'subtype' => 'single',
        'option_attributes' => [
            'option_type' => 'static',
            'option_data' => [
                'Y' => '승인 여부',
            ],
        ],
        'form_attributes' => [
            'detect_changed' => true,
        ],
        'list' => true,
    ],
	[
		'field' => 'withdraw_dt',
		'label' => 'lang:user.withdraw_dt',
		'form' => true,
		'rules' => 'trim',
		'errors' => [],
		'category' => 'basic',
		'type' => 'date',
		'subtype' => 'flatpickr',
		'icon' => null,
		'form_text' => '',
		'attributes' => [],
		'form_attributes' => [
			'detect_changed' => false,
		],
	],
	[
		'field' => 'recent_dt',
		'label' => 'lang:common.recent_dt',
		'form' => true,
		'rules' => 'trim',
		'errors' => [],
		'category' => 'basic',
		'type' => 'text',
		'subtype' => 'readonly',
		'icon' => 'ri-calendar-line',
		'form_text' => '',
		'attributes' => [
			'placeholder' => 'YYYY-MM-DD',
		],
		'form_attributes' => [
			'view_mod' => 'edit',
		],
		'list' => true,
	],
];


$config['form_works_config'] = [
	[
		'field' => 'article_id',
		'label' => 'lang:article.article_id',
		'form' => true,
		'rules' => 'trim|required_mod[edit]',
		'category' => 'basic',
		'type' => 'hidden',
		'subtype' => 'identifier',
		'list' => false,
	],
	[
		'field' => 'board_id',
		'label' => 'lang:board.board_id',
		'form' => true,
		'rules' => 'trim|required',
		'errors' => [],
		'category' => 'basic',
		'type' => 'hidden',
		'default' => 3,
		'list' => false,
	],
	[
		'field' => 'open_yn',
		'label' => 'lang:article.open_yn',
		'form' => true,
		'rules' => 'trim|required',
		'errors' => [],
		'category' => 'basic',
		'type' => 'hidden',
		'default' => 'N',
		'list' => false,
	],
	[
		'field' => 'subject',
		'label' => 'lang:article.subject',
		'form' => true,
		'rules' => 'trim|required|max_length[300]',
		'errors' => [],
		'category' => 'basic',
		'type' => 'text',
		'attributes' => [
			'readonly' => 'readonly',
		],
		'list' => true,
	],
	[
		'field' => 'content',
		'label' => 'lang:article.content',
		'form' => true,
		'rules' => 'trim|required',
		'errors' => [],
		'category' => 'basic',
		'type' => 'textarea',
		'attributes' => [
			'readonly' => 'readonly',
		],
		'list' => false,
	],
	[
		'field' => 'thumbnail',
		'label' => 'lang:epmagazine.thumbnail',
		'form' => true,
		'rules' => 'trim|required_if_empty_file[thumbnail|issue.thumbnail.issue_id]',
		'errors' => [],
		'category' => 'basic',
		'type' => 'file',
		'subtype' => 'thumbnail',
		'icon' => 'ri-file-image-line',
		'form_text' => [
			'line' => 'Upload File Only',
			'replace' => 'IMG',
			'icon' => 'ri-file-image-fill',
			'icon_size' => 16,
		],
		'attributes' => [
			'max' => 1,
			'accept' => 'image/jpeg,image/png',
			'multiple' => 'false',
		],
		'form_attributes' => [
			'with_list' => true,
			'list_delete' => 'thumbnail',
		],
		'list' => true,
		'list_attributes' => [
			'format' => 'img',
			'icon' => 'ri-image-fill',
			'onclick' => [
				'kind' => 'bs',
				'attrs' => [
					'toggle' => 'popover',
					'trigger' => 'hover',
					'placement' => 'right',
					'html' => 'true',
					'template' => '<div class="popover" role="tooltip"><div class="popover-arrow"></div><div class="popover-body p-0 rounded-3 overflow-hidden"></div></div>',
				]
			],
			'render' => []
		]
	],
//	[
//		'field' => 'reply',
//		'label' => 'lang:article.reply',
//		'form' => true,
//		'rules' => 'trim',
//		'errors' => [],
//		'category' => 'group',
//		'type' => 'textarea',
//		'subtype' => 'autosize',
//		'form_attributes' => [
//			'with_list' => true,
//			'list_delete' => false,
//			'list_field' => 'reply_list',
//			'list_type' => 'reply_list',
//		],
//		'group' => 'reply_list',
//		'group_attributes' => [
//			'label' => 'lang:article.reply',
//			'form_text' => '',
//			'type' => 'reply_list',
//			'key' => 'reply_content',
//			'envelope_name' => false,
//			'group_repeater' => false,
//		],
//		'list' => false,
//	],
	[
		'field' => 'created_id',
		'label' => 'lang:common.created_id',
		'form' => false,
		'list' => true,
	],
	[
		'field' => 'recent_dt',
		'label' => 'lang:common.recent_dt',
		'form' => true,
		'rules' => 'trim',
		'errors' => [],
		'category' => 'basic',
		'type' => 'text',
		'subtype' => 'readonly',
		'icon' => 'ri-calendar-line',
		'form_text' => '',
		'attributes' => [
			'placeholder' => 'YYYY-MM-DD',
		],
		'form_attributes' => [
			'view_mod' => 'edit',
		],
		'list' => true,
	],
];


$config['form_notices_config'] = [
	[
		'field' => 'article_id',
		'label' => 'lang:issue.article_id',
		'form' => true,
		'rules' => 'trim|required_mod[edit]',
		'category' => 'basic',
		'type' => 'hidden',
		'subtype' => 'identifier',
		'list' => false,
	],
	[
		'field' => 'board_id',
		'label' => 'lang:board.board_id',
		'form' => true,
		'rules' => 'trim|required',
		'errors' => [],
		'category' => 'basic',
		'type' => 'hidden',
		'default' => 1,
		'list' => false,
	],
	[
		'field' => 'open_yn',
		'label' => 'lang:article.open_yn',
		'form' => true,
		'rules' => 'trim|required',
		'errors' => [],
		'category' => 'basic',
		'type' => 'hidden',
		'default' => 'Y',
		'list' => false,
	],
	[
		'field' => 'subject',
		'label' => 'lang:article.subject',
		'form' => true,
		'rules' => 'trim|required|max_length[300]',
		'errors' => [],
		'category' => 'basic',
		'type' => 'text',
		'list' => true,
	],
	[
		'field' => 'content',
		'label' => 'lang:article.content',
		'form' => true,
		'rules' => 'trim|required',
		'errors' => [],
		'category' => 'basic',
		'type' => 'textarea',
		'subtype' => 'quill',
		'list' => false,
	],
	[
		'field' => 'uploads',
		'label' => 'lang:article.uploads',
		'form' => true,
		'rules' => 'trim',
		'errors' => [],
		'category' => 'basic',
		'type' => 'file',
		'icon' => '',
		'form_text' => [
			'line' => 'Upload Attachment',
			'replace' => '',
			'icon' => 'ri-attachment-2',
			'icon_size' => 16,
		],
		'form_attributes' => [
			'with_list' => true,
			'list_sorter' => true,
			'list_delete' => 'attachment',
		],
		'list' => false,
	],
	[
		'field' => 'recent_dt',
		'label' => 'lang:common.recent_dt',
		'form' => true,
		'rules' => 'trim',
		'errors' => [],
		'category' => 'basic',
		'type' => 'text',
		'subtype' => 'readonly',
		'icon' => 'ri-calendar-line',
		'form_text' => '',
		'attributes' => [
			'placeholder' => 'YYYY-MM-DD',
		],
		'form_attributes' => [
			'view_mod' => 'edit',
		],
		'list' => true,
	],
];

$config['form_inquiries_config'] = [
	[
		'field' => 'article_id',
		'label' => 'lang:article.article_id',
		'form' => true,
		'rules' => 'trim|required_mod[edit]',
		'category' => 'basic',
		'type' => 'hidden',
		'subtype' => 'identifier',
		'list' => false,
	],
	[
		'field' => 'board_id',
		'label' => 'lang:board.board_id',
		'form' => true,
		'rules' => 'trim|required',
		'errors' => [],
		'category' => 'basic',
		'type' => 'hidden',
		'default' => 2,
		'list' => false,
	],
	[
		'field' => 'open_yn',
		'label' => 'lang:article.open_yn',
		'form' => true,
		'rules' => 'trim|required',
		'errors' => [],
		'category' => 'basic',
		'type' => 'hidden',
		'default' => 'Y',
		'list' => false,
	],
	[
		'field' => 'subject',
		'label' => 'lang:article.subject',
		'form' => true,
		'rules' => 'trim|required|max_length[300]',
		'errors' => [],
		'category' => 'basic',
		'type' => 'text',
		'attributes' => [
			'readonly' => 'readonly',
		],
		'list' => true,
	],
	[
		'field' => 'content',
		'label' => 'lang:article.content',
		'form' => true,
		'rules' => 'trim|required',
		'errors' => [],
		'category' => 'basic',
		'type' => 'textarea',
		'attributes' => [
			'readonly' => 'readonly',
		],
		'list' => false,
	],
	[
		'field' => 'uploads',
		'label' => 'lang:article.uploads',
		'form' => true,
		'rules' => '',
		'errors' => [],
		'category' => 'basic',
		'type' => 'file',
		'subtype' => 'readonly',
		'icon' => '',
		'attributes' => [
			'max' => 1,
			'accept' => '*',
			'multiple' => 'false',
		],
		'form_attributes' => [
			'with_list' => true,
			'list_delete' => false,
		],
		'list' => true,
		'list_attributes' => [
			'format' => 'icon',
			'icon' => 'ri-file-download-fill',
			'onclick' => [
				'kind' => 'download',
			],
		],
	],
	[
		'field' => 'reply_yn',
		'label' => 'lang:article.reply_yn',
		'form' => false,
		'list' => true,
	],
	[
		'field' => 'reply',
		'label' => 'lang:article.reply',
		'form' => true,
		'rules' => 'trim',
		'errors' => [],
		'category' => 'group',
		'type' => 'textarea',
		'subtype' => 'autosize',
		'form_attributes' => [
			'with_list' => true,
			'list_delete' => false,
			'list_field' => 'reply_list',
			'list_type' => 'reply_list',
		],
		'group' => 'reply_list',
		'group_attributes' => [
			'label' => 'lang:article.reply',
			'form_text' => '',
			'type' => 'reply_list',
			'key' => 'reply_content',
			'envelope_name' => false,
			'group_repeater' => false,
		],
		'list' => false,
	],
	[
		'field' => 'created_id',
		'label' => 'lang:common.created_id',
		'form' => false,
		'list' => true,
	],
	[
		'field' => 'recent_dt',
		'label' => 'lang:common.recent_dt',
		'form' => true,
		'rules' => 'trim',
		'errors' => [],
		'category' => 'basic',
		'type' => 'text',
		'subtype' => 'readonly',
		'icon' => 'ri-calendar-line',
		'form_text' => '',
		'attributes' => [
			'placeholder' => 'YYYY-MM-DD',
		],
		'form_attributes' => [
			'view_mod' => 'edit',
		],
		'list' => true,
	],
];
