<?php defined('BASEPATH') or exit('No direct script access allowed');

require_once __DIR__.'/Common.php';

class ArticlePrefer extends Common
{
	function __construct()
	{
		parent::__construct();

		$this->load->model('Model_Article_Prefer', 'Model');
		$this->load->model('Model_User');

		$this->setProperties($this->Model);
	}

	protected function beforeGet()
	{
		$tokenData = $this->validateToken();

		$dto = parent::beforeGet(); // TODO: Change the autogenerated stub

		$dto['where']['user_id'] = $tokenData->user_id;

		return $dto;
	}

	protected function beforePut($key, $model = null)
	{
		$tokenData = $this->validateToken();

		$dto = parent::beforePut($key, $model); // TODO: Change the autogenerated stub

		$dto['user_id'] = $tokenData->user_id;

		return $dto;
	}
}
