<?php
$config['web_form_config_loaded'] = true;

$config['form_login_config'] = [
	[
		'field' => 'id',
		'label' => 'lang:user.id',
		'rules' => 'trim|required',
		'errors' => [],
		'category' => 'basic',
		'type' => 'text',
		'icon' => 'ri-user-line',
		'attributes' => [
			'autocapitalize' => 'none',
			'autocomplete' => 'off',
			'placeholder' => 'Enter The User ID',
		],
	],
	[
		'field' => 'password',
		'label' => 'lang:user.password',
		'rules' => 'trim|required',
		'errors' => [],
		'category' => 'basic',
		'type' => 'password',
		'attributes' => [
			'autocomplete' => 'new-password',
			'placeholder' => 'Password Dots',
		],
	],
	[
		'field' => 'autologin',
		'label' => 'lang:auth.autologin',
		'rules' => '',
		'errors' => [],
		'category' => 'basic',
		'type' => 'checkbox',
		'subtype' => 'single',
		'attributes' => [],
		'form_attributes' => [],
	],
];

$config['form_signup_config'] = [
	[
		'field' => 'user_cd',
		'label' => 'lang:user.user_cd',
		'form' => true,
		'rules' => 'trim',
		'category' => 'basic',
		'type' => 'hidden',
		'default' => 'USR002',
		'list' => false,
	],
	[
		'field' => 'id',
		'label' => 'lang:user.id',
		'rules' => 'trim|required|min_length[4]|is_unique[user.id.user_id]',
		'form' => true,
		'errors' => [],
		'category' => 'custom',
		'type' => 'text',
		'subtype' => 'unique',
		'icon' => 'ri-user-line',
		'form_text' => 'Please enter at least 4 characters',
		'attributes' => [
			'autocapitalize' => 'none',
			'autocomplete' => 'off',
			'placeholder' => 'Enter The User ID',
		],
		'form_attributes' => [
			'editable' => false,
			'with_btn' => true,
			'btn_type' => 'dup_check',
			'btn_params' => '{"key":"id", "title":"아이디"}',
			'text_type' => 'eng|num',
		],
		'list' => true,
	],
	[
		'field' => 'password',
		'label' => 'lang:user.password',
		'rules' => 'trim|required_mod[add]|min_length[4]|max_length[15]',
		'form' => true,
		'errors' => [],
		'category' => 'group',
		'type' => 'password',
		'icon' => 'svg:ri-lock-password-line',
		'form_text' => 'Please enter 4 to 15 characters, including letters and numbers',
		'attributes' => [
			'autocomplete' => 'new-password',
			'placeholder' => 'Password Dots',
		],
		'form_attributes' => [
			'detect_changed' => true,
		],
		'group' => 'user_password',
		'group_attributes' => [
			'envelope_name' => false,
			'label' => 'lang:user.password',
			'form_text' => '',
			'type' => 'new_password',
			'key' => 'password',
		],
		'list' => false,
	],
	[
		'field' => 'password_confirm',
		'label' => 'lang:user.password_confirm',
		'rules' => 'trim|required_mod[add]|matches[password]',
		'form' => true,
		'errors' => [],
		'category' => 'group',
		'type' => 'password',
		'subtype' => 'password_confirm',
		'icon' => 'svg:ri-lock-password-fill',
		'form_text' => 'Please Repeat The Password',
		'attributes' => [
			'autocomplete' => 'new-password',
			'placeholder' => 'Password Dots',
		],
		'form_attributes' => [
			'detect_changed' => true,
		],
		'group' => 'user_password',
		'group_attributes' => [
			'key' => 'password_confirm',
		],
		'list' => false,
	],
	[
		'field' => 'name',
		'label' => 'lang:user.name',
		'rules' => 'trim|required',
		'form' => true,
		'list' => true,
	],
	[
		'field' => 'email',
		'label' => 'lang:user.email',
		'rules' => 'trim|required|is_unique[user.email.user_id]',
		'form' => true,
		'category' => 'custom',
		'type' => 'text',
		'subtype' => 'unique',
		'icon' => 'ri-font-family',
		'attributes' => [
			'placeholder' => 'Enter The User Email',
		],
		'form_attributes' => [
			'editable' => false,
			'with_btn' => true,
			'btn_type' => 'dup_check',
			'btn_params' => '{"key":"email", "title":"이메일"}',
			'text_type' => 'email',
		],
		'list' => true,
	],
	[
		'field' => 'tel',
		'label' => 'lang:user.tel',
		'form' => true,
		'rules' => 'trim|required',
		'errors' => [],
		'category' => 'basic',
		'type' => 'tel',
		'subtype' => 'cleave-hp',
		'icon' => null,
		'form_text' => '',
		'attributes' => [],
		'default' => '',
		'list' => true,
		'list_attributes' => [],
	],
	[
		'field' => 'code',
		'label' => 'lang:student.code',
		'form' => true,
		'rules' => 'trim|required|exact_length[10]|integer|is_unique[admin.cert_no.admin_id]',
		'errors' => [],
		'category' => 'custom',
		'type' => 'text',
		'subtype' => 'unique',
		'icon' => 'ri-number-2',
		'form_text' => 'Enter The Student Code',
		'attributes' => [],
		'form_attributes' => [
			'with_btn' => true,
			'btn_type' => 'dup_check',
			'btn_params' => '{"key":"code", "title":"학번"}',
			'text_type' => 'num',
		],
		'default' => '',
		'list' => true,
		'list_attributes' => [],
	],
	[
		'field' => 'grade',
		'label' => 'lang:student.grade',
		'form' => true,
		'rules' => 'trim|required',
		'errors' => [],
		'category' => 'basic',
		'type' => 'select',
		'subtype' => 'selectpicker',
		'attributes' => [
			'placeholder' => 'Select The Grade',
		],
		'option_attributes' => [
			'option_type' => 'field',
		],
		'default' => '',
		'list' => true,
		'list_attributes' => [],
	],
	[
		'field' => 'disabilities_yn',
		'label' => 'lang:student.disabilities_yn',
		'form' => true,
		'rules' => 'trim',
		'errors' => [],
        'category' => 'basic',
        'type' => 'checkbox',
        'subtype' => 'single',
        'option_attributes' => [
            'option_type' => 'static',
            'option_data' => [
                'Y' => 'lang:student.disabilities_yn',
            ],
        ],
        'form_attributes' => [
            'detect_changed' => true,
        ],
		'default' => '',
		'list' => true,
		'list_attributes' => [],
	],
	[
		'field' => 'aac_yn',
		'label' => 'lang:student.aac_yn',
		'form' => true,
		'rules' => 'trim',
		'errors' => [],
        'category' => 'basic',
        'type' => 'checkbox',
        'subtype' => 'single',
        'option_attributes' => [
            'option_type' => 'static',
            'option_data' => [
                'Y' => 'lang:student.aac_yn',
            ],
        ],
        'form_attributes' => [
            'detect_changed' => true,
        ],
		'default' => '',
		'list' => true,
		'list_attributes' => [],
	],
];
