<?php defined('BASEPATH') or exit('No direct script access allowed');

require_once __DIR__ . '/Common.php';

class Articles extends Common
{
	public function __construct()
	{
		parent::__construct();

		$this->titleList[] = 'Articles Management';
		$this->addJsVars([
			'API_URI' => '/api/articles',
			'API_PARAMS' => []
		]);
	}

	protected function delData($key, $bool)
	{
		$data = $this->Model->getData([], [$this->identifier => $key]);

		if($data->thumbnail) {
			$this->delFileData(['file_id' => $data->thumbnail]);
		}

		$attachmentList = $this->Model_Article_Attachment->getList([],['article_id' => $key]);
		foreach ($attachmentList as $attachmentData) {
			$file_id = $attachmentData->file_id;
			$this->delFileData(['file_id' => $file_id]);
			$this->Model_Article_Attachment->delData([$this->identifier => $key, 'file_id' => $file_id]);
		}

		parent::delData($key, $bool);
	}

	public function deleteFile_patch($key = 0)
	{
		$type = $this->input->get('type') ?? null;
		$file_id = $this->patch('file_id') ?? null;
		if(!$type || !$file_id) $this->response(['code' => EMPTY_REQUIRED_DATA]);

		switch ($type) {
			case 'thumbnail' :
				$this->Model->modData(['thumbnail' => null], [$this->identifier => $key]);
				break;
			case 'attachment' :
				$this->Model_Article_Attachment->delData([$this->identifier => $key, 'file_id' => $file_id]);
				break;
		}

		parent::deleteFile_patch($key); // TODO: Change the autogenerated stub
	}
}
